---
- name: Create aws
  hosts: local
  connection: local
  gather_facts: False
  vars:
    keypair:
    instance_type: t2.micro
    image: ami-09558250a3419e7d0
    region: us-east-2
    count: 1
    vpc_subnet_id:
    security_group: Ansible-SecurityGroup
    aws_access_key: AKIAWL2XH4CZST7PKRUP
    aws_secret_key: 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

  tasks:
     - name: Create a security group
       ec2_group:
         name: "{{ security_group }}"
         description: Security group for Servers port 22
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"

     - name: Create AWS EC2
       ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         group: "{{ security_group }}"
         region: "{{ region }}"
         instance_tags:
           Name: Ansible AWS
           Type: Ansible EC2
         count: "{{ count }}"
         wait: true
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
       register: ec2
     - name: Print all ec2 variables
       debug: var=ec2
